name: Hello World
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello
        run: echo "Hello"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: printing world
        run: echo "world"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploying the app
        run: echo "deployed"
  
